create database QLNV;
USE QLNV;

create table PHONG (
	MAPHONG CHAR(3) NOT NULL PRIMARY KEY,
    TENPHONG NVARCHAR(40) NOT NULL,
    DIACHI NVARCHAR(50) NOT NULL,
    TEL CHAR(10) NOT NULL
);

create table DMNN (
	MANN CHAR(2) NOT NULL PRIMARY KEY,
    TENNN NVARCHAR(20) NOT NULL
);

create table NHANVIEN (
	MANV CHAR(5) NOT NULL PRIMARY KEY,
    HOTEN NVARCHAR(40) NOT NULL,
    GIOITINH CHAR(3) NOT NULL,
    NGAYSINH DATETIME NOT NULL,
    LUONG INT NOT NULL,
    MAPHONG CHAR(3) NOT NULL,
    SDT CHAR(10) NOT NULL,
    NGAYBC DATETIME NOT NULL
);

create table TDNN (
	MANV CHAR(5),
	MANN CHAR(2),
    TDO CHAR(1) NOT NULL,
    primary key (MANV, MANN)
)
